### ISSUE TITLE
Oracle Driver version

### ISSUE THREAD

**Issue by gkawamoto** [joaoleite/redash_oracle#1]
Apparently the redash code is built specifically to the 5.2 version of cx_Oracle. Could you change the Dockerfile to install `pip install cx_Oracle==5.2`?

Thanks!

**Comment by joaoleite** [comment]
Hi @gkawamoto 

It was updated but I forgot to close it .. 2 years later ... cleaning the house ... closing the issue :)

Tks 4 all
